/* Automatically generated by tree-sitter v0.25.1 (f5afe475deb7c0bae6407fb776c76824f717bb61) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_skip = 1,
  anon_sym_local = 2,
  anon_sym_in = 3,
  anon_sym_end = 4,
  anon_sym_EQ = 5,
  anon_sym_if = 6,
  anon_sym_then = 7,
  anon_sym_else = 8,
  anon_sym_case = 9,
  anon_sym_of = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_proc = 13,
  anon_sym_DOLLAR = 14,
  anon_sym_PLUS = 15,
  anon_sym_DASH = 16,
  anon_sym_STAR = 17,
  anon_sym_SLASH = 18,
  sym_identifier = 19,
  anon_sym_LPAREN = 20,
  anon_sym_COLON = 21,
  anon_sym_RPAREN = 22,
  sym_number = 23,
  anon_sym_DQUOTE = 24,
  aux_sym_string_token1 = 25,
  sym_bool = 26,
  sym_atom = 27,
  sym_source_file = 28,
  sym__definition = 29,
  sym_block = 30,
  sym__statement = 31,
  sym_local_definition = 32,
  sym_assignment = 33,
  sym_if_statement = 34,
  sym_case_statement = 35,
  sym_procedure_application = 36,
  sym__expression = 37,
  sym_procedure_definition = 38,
  sym_add = 39,
  sym_subtract = 40,
  sym_multiply = 41,
  sym_divide = 42,
  sym_negate = 43,
  sym__type = 44,
  sym_record = 45,
  sym_tuple = 46,
  sym_string = 47,
  sym__literal = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym__definition_repeat1 = 50,
  aux_sym_local_definition_repeat1 = 51,
  aux_sym_record_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_skip] = "skip",
  [anon_sym_local] = "local",
  [anon_sym_in] = "in",
  [anon_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_case] = "case",
  [anon_sym_of] = "of",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_proc] = "proc",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_bool] = "bool",
  [sym_atom] = "atom",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym_local_definition] = "local_definition",
  [sym_assignment] = "assignment",
  [sym_if_statement] = "if_statement",
  [sym_case_statement] = "case_statement",
  [sym_procedure_application] = "procedure_application",
  [sym__expression] = "_expression",
  [sym_procedure_definition] = "procedure_definition",
  [sym_add] = "add",
  [sym_subtract] = "subtract",
  [sym_multiply] = "multiply",
  [sym_divide] = "divide",
  [sym_negate] = "negate",
  [sym__type] = "_type",
  [sym_record] = "record",
  [sym_tuple] = "tuple",
  [sym_string] = "string",
  [sym__literal] = "_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__definition_repeat1] = "_definition_repeat1",
  [aux_sym_local_definition_repeat1] = "local_definition_repeat1",
  [aux_sym_record_repeat1] = "record_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_skip] = sym_skip,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_case] = anon_sym_case,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_proc] = anon_sym_proc,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_bool] = sym_bool,
  [sym_atom] = sym_atom,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym_local_definition] = sym_local_definition,
  [sym_assignment] = sym_assignment,
  [sym_if_statement] = sym_if_statement,
  [sym_case_statement] = sym_case_statement,
  [sym_procedure_application] = sym_procedure_application,
  [sym__expression] = sym__expression,
  [sym_procedure_definition] = sym_procedure_definition,
  [sym_add] = sym_add,
  [sym_subtract] = sym_subtract,
  [sym_multiply] = sym_multiply,
  [sym_divide] = sym_divide,
  [sym_negate] = sym_negate,
  [sym__type] = sym__type,
  [sym_record] = sym_record,
  [sym_tuple] = sym_tuple,
  [sym_string] = sym_string,
  [sym__literal] = sym__literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__definition_repeat1] = aux_sym__definition_repeat1,
  [aux_sym_local_definition_repeat1] = aux_sym_local_definition_repeat1,
  [aux_sym_record_repeat1] = aux_sym_record_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_skip] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_case] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_proc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_local_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_case_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure_application] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_procedure_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_subtract] = {
    .visible = true,
    .named = true,
  },
  [sym_multiply] = {
    .visible = true,
    .named = true,
  },
  [sym_divide] = {
    .visible = true,
    .named = true,
  },
  [sym_negate] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_local_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 58,
        '$', 47,
        '(', 53,
        ')', 55,
        '*', 50,
        '+', 48,
        '-', 49,
        '/', 51,
        ':', 54,
        '=', 37,
        'c', 4,
        'e', 20,
        'f', 5,
        'i', 14,
        'l', 23,
        'o', 15,
        'p', 26,
        's', 18,
        't', 16,
        '{', 43,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '-') ADVANCE(49);
      if (lookahead == 'f') ADVANCE(64);
      if (lookahead == 'p') ADVANCE(69);
      if (lookahead == 't') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == ')') ADVANCE(55);
      if (lookahead == 'f') ADVANCE(64);
      if (lookahead == 't') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'k') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 31:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_skip);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_case);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_proc);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_proc);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_bool);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_bool);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'a') ADVANCE(67);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'c') ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'e') ADVANCE(62);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'l') ADVANCE(71);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'o') ADVANCE(65);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'r') ADVANCE(68);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'r') ADVANCE(72);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 's') ADVANCE(66);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'u') ADVANCE(66);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_atom);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 59},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_skip] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_case] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_proc] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_bool] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(61),
    [sym__definition] = STATE(9),
    [sym__statement] = STATE(9),
    [sym_local_definition] = STATE(9),
    [sym_assignment] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_case_statement] = STATE(9),
    [sym_procedure_application] = STATE(9),
    [sym_procedure_definition] = STATE(33),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym__definition_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_skip] = ACTIONS(5),
    [anon_sym_local] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_case] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_proc] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(19), 1,
      anon_sym_proc,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym__literal,
    ACTIONS(23), 2,
      sym_identifier,
      sym_number,
    ACTIONS(27), 2,
      sym_bool,
      sym_atom,
    STATE(41), 11,
      sym__expression,
      sym_procedure_definition,
      sym_add,
      sym_subtract,
      sym_multiply,
      sym_divide,
      sym_negate,
      sym__type,
      sym_record,
      sym_tuple,
      sym_string,
  [34] = 7,
    ACTIONS(19), 1,
      anon_sym_proc,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym__literal,
    ACTIONS(27), 2,
      sym_bool,
      sym_atom,
    ACTIONS(29), 2,
      sym_identifier,
      sym_number,
    STATE(26), 11,
      sym__expression,
      sym_procedure_definition,
      sym_add,
      sym_subtract,
      sym_multiply,
      sym_divide,
      sym_negate,
      sym__type,
      sym_record,
      sym_tuple,
      sym_string,
  [68] = 7,
    ACTIONS(19), 1,
      anon_sym_proc,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym__literal,
    ACTIONS(27), 2,
      sym_bool,
      sym_atom,
    ACTIONS(31), 2,
      sym_identifier,
      sym_number,
    STATE(31), 11,
      sym__expression,
      sym_procedure_definition,
      sym_add,
      sym_subtract,
      sym_multiply,
      sym_divide,
      sym_negate,
      sym__type,
      sym_record,
      sym_tuple,
      sym_string,
  [102] = 7,
    ACTIONS(19), 1,
      anon_sym_proc,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym__literal,
    ACTIONS(27), 2,
      sym_bool,
      sym_atom,
    ACTIONS(33), 2,
      sym_identifier,
      sym_number,
    STATE(25), 11,
      sym__expression,
      sym_procedure_definition,
      sym_add,
      sym_subtract,
      sym_multiply,
      sym_divide,
      sym_negate,
      sym__type,
      sym_record,
      sym_tuple,
      sym_string,
  [136] = 7,
    ACTIONS(19), 1,
      anon_sym_proc,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym__literal,
    ACTIONS(27), 2,
      sym_bool,
      sym_atom,
    ACTIONS(35), 2,
      sym_identifier,
      sym_number,
    STATE(24), 11,
      sym__expression,
      sym_procedure_definition,
      sym_add,
      sym_subtract,
      sym_multiply,
      sym_divide,
      sym_negate,
      sym__type,
      sym_record,
      sym_tuple,
      sym_string,
  [170] = 7,
    ACTIONS(19), 1,
      anon_sym_proc,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym__literal,
    ACTIONS(27), 2,
      sym_bool,
      sym_atom,
    ACTIONS(37), 2,
      sym_identifier,
      sym_number,
    STATE(22), 11,
      sym__expression,
      sym_procedure_definition,
      sym_add,
      sym_subtract,
      sym_multiply,
      sym_divide,
      sym_negate,
      sym__type,
      sym_record,
      sym_tuple,
      sym_string,
  [204] = 7,
    ACTIONS(19), 1,
      anon_sym_proc,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym__literal,
    ACTIONS(27), 2,
      sym_bool,
      sym_atom,
    ACTIONS(39), 2,
      sym_identifier,
      sym_number,
    STATE(23), 11,
      sym__expression,
      sym_procedure_definition,
      sym_add,
      sym_subtract,
      sym_multiply,
      sym_divide,
      sym_negate,
      sym__type,
      sym_record,
      sym_tuple,
      sym_string,
  [238] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(11), 9,
      sym__definition,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym_source_file_repeat1,
      aux_sym__definition_repeat1,
  [277] = 10,
    ACTIONS(47), 1,
      sym_skip,
    ACTIONS(50), 1,
      anon_sym_local,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(56), 1,
      anon_sym_case,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(62), 1,
      anon_sym_proc,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(33), 1,
      sym_procedure_definition,
    ACTIONS(45), 3,
      ts_builtin_sym_end,
      anon_sym_end,
      anon_sym_else,
    STATE(10), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [316] = 10,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      sym_skip,
    ACTIONS(73), 1,
      anon_sym_local,
    ACTIONS(76), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_case,
    ACTIONS(82), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      anon_sym_proc,
    ACTIONS(88), 1,
      sym_identifier,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(11), 9,
      sym__definition,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym_source_file_repeat1,
      aux_sym__definition_repeat1,
  [355] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(91), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    ACTIONS(93), 2,
      anon_sym_end,
      anon_sym_else,
    STATE(10), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [393] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(60), 1,
      sym_block,
    STATE(12), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [430] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(66), 1,
      sym_block,
    STATE(12), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [467] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(49), 1,
      sym_block,
    STATE(12), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [504] = 2,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [525] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(57), 1,
      sym_block,
    STATE(12), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [562] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(58), 1,
      sym_block,
    STATE(12), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [599] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(64), 1,
      sym_block,
    STATE(12), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [636] = 10,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_case,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_proc,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_skip,
    STATE(33), 1,
      sym_procedure_definition,
    STATE(53), 1,
      sym_block,
    STATE(12), 7,
      sym__statement,
      sym_local_definition,
      sym_assignment,
      sym_if_statement,
      sym_case_statement,
      sym_procedure_application,
      aux_sym__definition_repeat1,
  [673] = 1,
    ACTIONS(101), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [691] = 3,
    ACTIONS(105), 1,
      anon_sym_STAR,
    ACTIONS(107), 1,
      anon_sym_SLASH,
    ACTIONS(103), 13,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_identifier,
  [713] = 1,
    ACTIONS(109), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [731] = 3,
    ACTIONS(105), 1,
      anon_sym_STAR,
    ACTIONS(107), 1,
      anon_sym_SLASH,
    ACTIONS(111), 13,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_identifier,
  [753] = 1,
    ACTIONS(113), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [771] = 1,
    ACTIONS(115), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [789] = 1,
    ACTIONS(117), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [807] = 1,
    ACTIONS(119), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [825] = 1,
    ACTIONS(121), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [843] = 1,
    ACTIONS(123), 15,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [861] = 5,
    ACTIONS(105), 1,
      anon_sym_STAR,
    ACTIONS(107), 1,
      anon_sym_SLASH,
    ACTIONS(127), 1,
      anon_sym_PLUS,
    ACTIONS(129), 1,
      anon_sym_DASH,
    ACTIONS(125), 10,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      sym_identifier,
  [886] = 1,
    ACTIONS(131), 10,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      sym_identifier,
  [899] = 1,
    ACTIONS(133), 10,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      sym_identifier,
  [912] = 1,
    ACTIONS(135), 10,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      sym_identifier,
  [925] = 1,
    ACTIONS(137), 10,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      sym_identifier,
  [938] = 1,
    ACTIONS(139), 10,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      sym_identifier,
  [951] = 1,
    ACTIONS(141), 10,
      ts_builtin_sym_end,
      sym_skip,
      anon_sym_local,
      anon_sym_end,
      anon_sym_if,
      anon_sym_else,
      anon_sym_case,
      anon_sym_LBRACE,
      anon_sym_proc,
      sym_identifier,
  [964] = 5,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      sym_number,
    STATE(40), 1,
      aux_sym_record_repeat1,
    STATE(45), 1,
      aux_sym_local_definition_repeat1,
    ACTIONS(147), 2,
      sym_bool,
      sym_atom,
  [981] = 3,
    ACTIONS(151), 1,
      sym_identifier,
    STATE(39), 1,
      aux_sym_local_definition_repeat1,
    ACTIONS(149), 3,
      anon_sym_in,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [993] = 4,
    ACTIONS(145), 1,
      sym_number,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_record_repeat1,
    ACTIONS(147), 2,
      sym_bool,
      sym_atom,
  [1007] = 5,
    ACTIONS(105), 1,
      anon_sym_STAR,
    ACTIONS(107), 1,
      anon_sym_SLASH,
    ACTIONS(127), 1,
      anon_sym_PLUS,
    ACTIONS(129), 1,
      anon_sym_DASH,
    ACTIONS(156), 1,
      anon_sym_then,
  [1023] = 4,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    ACTIONS(160), 1,
      sym_number,
    STATE(42), 1,
      aux_sym_record_repeat1,
    ACTIONS(163), 2,
      sym_bool,
      sym_atom,
  [1037] = 2,
    ACTIONS(166), 2,
      anon_sym_RPAREN,
      sym_number,
    ACTIONS(168), 2,
      sym_bool,
      sym_atom,
  [1046] = 3,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
    ACTIONS(172), 1,
      sym_identifier,
    STATE(48), 1,
      aux_sym_local_definition_repeat1,
  [1056] = 3,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_local_definition_repeat1,
  [1066] = 3,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_in,
    STATE(39), 1,
      aux_sym_local_definition_repeat1,
  [1076] = 3,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_local_definition_repeat1,
  [1086] = 3,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_local_definition_repeat1,
  [1096] = 2,
    ACTIONS(184), 1,
      anon_sym_end,
    ACTIONS(186), 1,
      anon_sym_else,
  [1103] = 2,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(47), 1,
      aux_sym_local_definition_repeat1,
  [1110] = 2,
    ACTIONS(190), 1,
      sym_identifier,
    STATE(46), 1,
      aux_sym_local_definition_repeat1,
  [1117] = 1,
    ACTIONS(192), 2,
      anon_sym_DOLLAR,
      sym_identifier,
  [1122] = 1,
    ACTIONS(194), 1,
      anon_sym_end,
  [1126] = 1,
    ACTIONS(196), 1,
      anon_sym_COLON,
  [1130] = 1,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
  [1134] = 1,
    ACTIONS(200), 1,
      anon_sym_of,
  [1138] = 1,
    ACTIONS(202), 1,
      anon_sym_else,
  [1142] = 1,
    ACTIONS(204), 1,
      anon_sym_end,
  [1146] = 1,
    ACTIONS(206), 1,
      anon_sym_EQ,
  [1150] = 1,
    ACTIONS(208), 1,
      anon_sym_end,
  [1154] = 1,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
  [1158] = 1,
    ACTIONS(212), 1,
      anon_sym_then,
  [1162] = 1,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
  [1166] = 1,
    ACTIONS(216), 1,
      anon_sym_end,
  [1170] = 1,
    ACTIONS(218), 1,
      aux_sym_string_token1,
  [1174] = 1,
    ACTIONS(220), 1,
      anon_sym_end,
  [1178] = 1,
    ACTIONS(222), 1,
      sym_identifier,
  [1182] = 1,
    ACTIONS(224), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 170,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 238,
  [SMALL_STATE(10)] = 277,
  [SMALL_STATE(11)] = 316,
  [SMALL_STATE(12)] = 355,
  [SMALL_STATE(13)] = 393,
  [SMALL_STATE(14)] = 430,
  [SMALL_STATE(15)] = 467,
  [SMALL_STATE(16)] = 504,
  [SMALL_STATE(17)] = 525,
  [SMALL_STATE(18)] = 562,
  [SMALL_STATE(19)] = 599,
  [SMALL_STATE(20)] = 636,
  [SMALL_STATE(21)] = 673,
  [SMALL_STATE(22)] = 691,
  [SMALL_STATE(23)] = 713,
  [SMALL_STATE(24)] = 731,
  [SMALL_STATE(25)] = 753,
  [SMALL_STATE(26)] = 771,
  [SMALL_STATE(27)] = 789,
  [SMALL_STATE(28)] = 807,
  [SMALL_STATE(29)] = 825,
  [SMALL_STATE(30)] = 843,
  [SMALL_STATE(31)] = 861,
  [SMALL_STATE(32)] = 886,
  [SMALL_STATE(33)] = 899,
  [SMALL_STATE(34)] = 912,
  [SMALL_STATE(35)] = 925,
  [SMALL_STATE(36)] = 938,
  [SMALL_STATE(37)] = 951,
  [SMALL_STATE(38)] = 964,
  [SMALL_STATE(39)] = 981,
  [SMALL_STATE(40)] = 993,
  [SMALL_STATE(41)] = 1007,
  [SMALL_STATE(42)] = 1023,
  [SMALL_STATE(43)] = 1037,
  [SMALL_STATE(44)] = 1046,
  [SMALL_STATE(45)] = 1056,
  [SMALL_STATE(46)] = 1066,
  [SMALL_STATE(47)] = 1076,
  [SMALL_STATE(48)] = 1086,
  [SMALL_STATE(49)] = 1096,
  [SMALL_STATE(50)] = 1103,
  [SMALL_STATE(51)] = 1110,
  [SMALL_STATE(52)] = 1117,
  [SMALL_STATE(53)] = 1122,
  [SMALL_STATE(54)] = 1126,
  [SMALL_STATE(55)] = 1130,
  [SMALL_STATE(56)] = 1134,
  [SMALL_STATE(57)] = 1138,
  [SMALL_STATE(58)] = 1142,
  [SMALL_STATE(59)] = 1146,
  [SMALL_STATE(60)] = 1150,
  [SMALL_STATE(61)] = 1154,
  [SMALL_STATE(62)] = 1158,
  [SMALL_STATE(63)] = 1162,
  [SMALL_STATE(64)] = 1166,
  [SMALL_STATE(65)] = 1170,
  [SMALL_STATE(66)] = 1174,
  [SMALL_STATE(67)] = 1178,
  [SMALL_STATE(68)] = 1182,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__definition_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__definition_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__definition_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__definition_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__definition_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__definition_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__definition_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__definition_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_divide, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtract, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiply, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negate, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_definition, 7, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_definition, 6, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_application, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_definition, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 8, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_local_definition_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_local_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [210] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_oz(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "oz",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
